server:
  port: 7002
  error:
    include-message: always

spring:
  data:
    mongodb:
      # this is important for enable unique business key checking
      auto-index-creation: true

logging:
  level:
    root: INFO
    se.magnus: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

---
spring.config.activate.on-profile: docker

server.port: 8080